### ISSUE TITLE
Cannot set xff_trusted_hops in helm/k8s deployments

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#198]
In docker-compose deployments, `xff_trusted_hops` is set in envoy's config (https://github.com/curiefense/curiefense/blob/main/curiefense/curieproxy/envoy.yaml.head#L39) by a [bootstrap script](https://github.com/curiefense/curiefense/blob/main/curiefense/images/curieproxy-envoy/init/start_curiefense.sh#L17).

With istio deployments, routes are not static: they are defined through [rds](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/rds).

I have tried defining an EnvoyFilter to add `xff_trusted_hops` as metadata to the route, mimicking data that we set in docker-compose environments.

Here is the filter I defined:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: curiefense-xff-filter-2
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      curiefense: "enabled"
  configPatches:
  - applyTo: HTTP_ROUTE
    # XXX maybe add match
    patch:
      operation: MERGE
      value:
        metadata:
          filter_metadata:
            envoy.filters.http.lua:
              xff_trusted_hops: "2"
```

With that filter, I can see `xff_trusted_hops` in a config dump (`istioctl dashboard envoy istio-ingressgateway-7fbb468d55-2hp5j.istio-system`):
```
   "dynamic_route_configs": [
    {
     "version_info": "2021-02-27T22:51:56Z/12",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "http.80",
      "virtual_hosts": [
       {
        "name": "*:80",
        "domains": [
         "*",
         "*:80"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/",
           "case_sensitive": true
          },
          "route": {
           "cluster": "outbound|9080||productpage.bookinfo.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "metadata": {
           "filter_metadata": {
            "envoy.filters.http.lua": {
             "xff_trusted_hops": "2"
            },
            "istio": {
             "config": "/apis/networking.istio.io/v1alpha3/namespaces/bookinfo/virtual-service/bookinfo"
            }
...
```

However, curieproxy never receives that metadata value in https://github.com/curiefense/curiefense/blob/main/curiefense/curieproxy/lua/utils.lua (I have added print() statements at this point to make sure).

This might be an envoy bug (it's an old version), or something wrong with my EnvoyFilter... Would it be acceptable to retrieve `xff_trusted_hops` from the environment, globally and not per-route, at least until we can find a better way of doing this?

**Comment by flaper87** [comment]
@xavier-rbz is this still relevant? perhaps it will be fixed as part of #221 ?

**Comment by xavier-rbz** [comment]
Yes, this is still relevant: it is an important feature for deployment, which justifies tracking with this issues IMO. It's not clear now whether #221 will fix that.

**Comment by flaper87** [comment]
> Yes, this is still relevant: it is an important feature for deployment, which justifies tracking with this issues IMO. It's not clear now whether #221 will fix that.

awesome, thanks for confirming. I'll see if I can spare some cycles to help with this task.

**Comment by ItaiPrajgrod** [comment]
@xavier-rbz what is the status of this issue? it seems we can close it

**Comment by xavier-rbz** [comment]
Yes, it can be closed. This value can be set using an EnvoyFilter such as this one:
```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    labels:
      app.kubernetes.io/name: istio
    name: accesslog-settings
    namespace: istio-system
  spec:
    configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            skip_xff_append: false
            use_remote_address: true
            xff_num_trusted_hops: 1
```
