### ISSUE TITLE
s3cfg not created in confserver

### ISSUE THREAD

**Issue by GabrielLasso** [curiefense/curiefense#415]
**Describe the bug**
I got a 403 when publish the changes do s3. "Error publishing to this bucket: CloudStorageError('403: Forbidden')!"

When @tzuryby looked, he found that there the file s3cgf was not in /run/secrets in confserver.

I deployed again from 55680abbb994d5435c2614bbfb45b512cd8e51a7 and it was not created.

**To Reproduce**

**Expected behavior**
Create s3cfg and send the changes to s3.

**Screenshots**
![Capturar_select-area_20210705154553](https://user-images.githubusercontent.com/12103372/124509310-1b779c80-dda8-11eb-9ce4-163175ce99dd.png)
![Capturar_select-area_20210705154519](https://user-images.githubusercontent.com/12103372/124509318-1c103300-dda8-11eb-97e6-a1f625630523.png)
![Capturar_select-area_20210705154623](https://user-images.githubusercontent.com/12103372/124509355-2af6e580-dda8-11eb-9310-9c4c01161c6b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Running on GKE
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"archive", BuildDate:"2021-06-17T08:45:43Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-gke.1600", GitCommit:"7b8e568a7fb4c9d199c2ba29a5f7d76f6b4341c2", GitTreeState:"clean", BuildDate:"2021-05-07T09:18:53Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jdorfman** [comment]
@flaper87 this bug was discovered while @tzuryby and I were on an office hours call with @GabrielLasso.

**Comment by flaper87** [comment]
@GabrielLasso thanks for filing this issue.

@GabrielLasso @tzuryby @jdorfman would it be possible to have the steps to reproduce this issue? I see it was deployed on GKE but I wonder if some scripts were used.

Note that we don't create this file, we just "make sure" it is mounted. For example, the helm charts expect an `s3cfg` secret to exist so that it can be mounted:

https://github.com/curiefense/curiefense-helm/blob/987ac81fae91c95e18deb8868b5520236116a8e5/curiefense-helm/curiefense/charts/curiefense-admin/templates/confserver-statefulset.yaml#L117-L124

https://github.com/curiefense/curiefense-helm/blob/987ac81fae91c95e18deb8868b5520236116a8e5/istio-helm/charts/gateways/istio-ingress/templates/deployment.yaml#L392-L399

Another question:

- Do you have `curiefense_bucket_type` set to `s3` in your values file? I'm surprised curieconf started at all since I would have expected the POD to fail if the secret is not there. 

- Another option is that the secret exists but it doesn't have the right key? `s3cfg`

**Comment by GabrielLasso** [comment]
> Do you have curiefense_bucket_type set to s3 in your values file? I'm surprised curieconf started at all since I would have expected the POD to fail if the secret is not there.

@flaper87 yes, the `curiefense_bucket_type` is set to `s3`. To deploy, I used the deploy.sh with DOCKER_TAG=main.

It is strange that `` shows this:
```
...
    volumeMounts:
    - mountPath: /uwsgi
      name: uwsgi-socket
    - mountPath: /run/secrets/s3cfg
      name: s3cfg
    - mountPath: /config
      name: persistent-confdb
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2wz2z
      readOnly: true
...
  volumes:
  - name: persistent-confdb
    persistentVolumeClaim:
      claimName: persistent-confdb-confserver-0
  - name: s3cfg
    secret:
      defaultMode: 420
      items:
      - key: s3cfg
        path: s3cfg
      secretName: s3cfg
  - emptyDir: {}
    name: uwsgi-socket
  - name: default-token-2wz2z
    secret:
      defaultMode: 420
      secretName: default-token-2wz2z
...
```

But `kubectl exec confserver-0 -n curiefense -it -- ls /run/secrets` shows
```
Defaulted container "confserver-nginx" out of: confserver-nginx, confserver-uwsgi, bootstrap-deploy (init)
kubernetes.io
```

> Another option is that the secret exists but it doesn't have the right key? s3cfg

I am using a key that has read/write access only to the s3://xxxxxx/curiefense/ folder, it might not cause an error, right?
