### ISSUE TITLE
Install curiefense in existing istio cluster

### ISSUE THREAD

**Issue by GabrielLasso** [curiefense/curiefense#536]
**Is your feature request related to a problem? Please describe.**
I want to install curiefense in a cluster that already has istio installed. A successfully installed curiefense itself using the helm charts. But when I try to run `DOCKER_TAG=main ./deploy.sh` in the `istio-helm`, it tries to reinstall istio, instead of just apply the necessary changes.

Then I got some errors like this:

```
...
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "istio-reader-service-account" in namespace "istio-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istio-base"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"
Release "istiod" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodDisruptionBudget "istiod" in namespace "istio-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istiod"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"
history.go:56: [debug] getting history for release istio-ingress
Release "istio-ingress" does not exist. Installing it now.
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/glasso/dev/curiefense-helm/istio-helm/charts/gateways/istio-ingress

Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodDisruptionBudget "istio-ingressgateway" in namespace "istio-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "istio-ingress"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-system"
...
```

A valid workout would be to uninstall istio, but that would change the IP of the loadbalancer (running in GCE) that is used in the ingress, and the IP is accesses by hundreds of domains so it can't de done.

**Describe the solution you'd like**
I'd like to have a simple way to configure istio so it sends the traffic to curiefense without reinstalling it.

**Describe alternatives you've considered**

**Additional context**

**Comment by GabrielLasso** [comment]
I edited the label `app.kubernetes.io/managed-by` and the annotations `meta.helm.sh/release-name` and `meta.helm.sh/release-namespace` in every existing istio resource to make Helm think it owns the resources, then I was able to install

It'd be nice to have this documented somewhere :smiley:

**Comment by jdorfman** [comment]
@GabrielLasso thanks for sharing. Is this something you would consider a work-around/hack or is this part of a bigger issue we need to address?

**Comment by GabrielLasso** [comment]
@jdorfman I think it is a valid use case (install in an existing istio cluster/mesh) that is not covered by neither installation [here](https://docs.curiefense.io/installation/deployment-first-steps/).

I had to manually hack istio to make it work

**Comment by MicroOps-cn** [comment]
You can try the patch below. (Unofficially provided methods.)，Compatibility needs to be self tested.
```yaml
# curiefense-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio-ingress
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "IngressGateways"
    curiefense: enabled
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
        heritage: Tiller
        release: istio
        chart: gateways
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
        istio.io/rev: default
        install.operator.istio.io/owning-resource: unknown
        operator.istio.io/component: "IngressGateways"
        sidecar.istio.io/inject: "false"
        curiefense: enabled
      annotations:
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/stats/prometheus"
        sidecar.istio.io/inject: "false"
    spec:
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        fsGroup: 1337
      serviceAccountName: istio-ingressgateway-service-account
      initContainers:
        - name: curiesync-initialpull
          image: "curiefense/curiesync:main"
          env:
            - name: CURIE_BUCKET_LINK
              value: "file:///bucket/prod/manifest.json"
            - name: CURIESYNC_QUIET
              value: "true"
            - name: RUN_MODE
              value: "SYNC_ONCE"
          imagePullPolicy:
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /bucket
              name: local-bucket
            - mountPath: /cf-config
              name: curiefense-config
      containers:
        - name: curiesync
          image: "curiefense/curiesync:main"
          env:
            - name: CURIE_BUCKET_LINK
              value: file:///bucket/prod/manifest.json
            - name: CURIESYNC_QUIET
              value: "true"
            - name: RUN_MODE
              value: "PERIODIC_SYNC"
          imagePullPolicy:
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "60Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /bucket
              name: local-bucket
            - mountPath: /cf-config
              name: curiefense-config
        - name: istio-proxy
          image: "wiseasy/curieproxy-istio:1.13.2.0"
          ports:
            - containerPort: 15021
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 15012
              protocol: TCP
            - containerPort: 15443
              protocol: TCP
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
          args:
            - proxy
            - router
            - --domain
            - $(POD_NAMESPACE).svc.cluster.local
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --log_output_level=default:info
            - --serviceCluster
            - istio-ingressgateway
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: JWT_POLICY
              value: third-party-jwt
            - name: PILOT_CERT_PROVIDER
              value: istiod
            - name: CA_ADDR
              value: istiod.istio-system.svc:15012
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: CANONICAL_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service.istio.io/canonical-name']
            - name: CANONICAL_REVISION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['service.istio.io/canonical-revision']
            - name: ISTIO_META_WORKLOAD_NAME
              value: istio-ingressgateway
            - name: ISTIO_META_OWNER
              value: kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
            - name: ISTIO_META_UNPRIVILEGED_POD
              value: "true"
            # - name: REDIS_HOST   # Redis domain Or IP
            #   value: "192.168.122.1"
            # - name: REDIS_PASSWORD
            #   value: "xxxxxxxxxxxxxxxxxxxxxxxxxx"  # Redis Password
            # - name: REDIS_DB
            #  value: "13"
            - name: ISTIO_META_ROUTER_MODE
              value: standard
            - name: ISTIO_META_CLUSTER_ID
              value: "Kubernetes"
          volumeMounts:
            - name: curiefense-config
              mountPath: /cf-config
            - name: istio-envoy
              mountPath: /etc/istio/proxy
            - name: config-volume
              mountPath: /etc/istio/config
            - mountPath: /var/run/secrets/istio
              name: istiod-ca-cert
            - name: istio-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
            - mountPath: /var/lib/istio/data
              name: istio-data
            - name: podinfo
              mountPath: /etc/istio/pod
            - name: ingressgateway-certs
              mountPath: "/etc/istio/ingressgateway-certs"
              readOnly: true
            - name: ingressgateway-ca-certs
              mountPath: "/etc/istio/ingressgateway-ca-certs"
              readOnly: true
      volumes:
        - name: local-bucket
          hostPath:
            path: /bucket
            type: DirectoryOrCreate
        - name: curiefense-config
          emptyDir: {}
        - name: istiod-ca-cert
          configMap:
            name: istio-ca-root-cert
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "cpu-limit"
                resourceFieldRef:
                  containerName: istio-proxy
                  resource: limits.cpu
                  divisor: 1m
              - path: "cpu-request"
                resourceFieldRef:
                  containerName: istio-proxy
                  resource: requests.cpu
                  divisor: 1m
        - name: istio-envoy
          emptyDir: {}
        - name: istio-data
          emptyDir: {}
        - name: istio-token
          projected:
            sources:
              - serviceAccountToken:
                  path: istio-token
                  expirationSeconds: 43200
                  audience: istio-ca
        - name: config-volume
          configMap:
            name: istio
            optional: true
        - name: ingressgateway-certs
          secret:
            secretName: "istio-ingressgateway-certs"
            optional: true
        - name: ingressgateway-ca-certs
          secret:
            secretName: "istio-ingressgateway-ca-certs"
            optional: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - "amd64"
                      - "ppc64le"
                      - "s390x"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - "amd64"
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - "ppc64le"
            - weight: 2
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - "s390x"
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: curiefense-lua-filter
  namespace: istio-system
  labels:
spec:
  workloadSelector:
    labels:
      curiefense: "enabled"
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              local session = require "lua.session_envoy"
              function envoy_on_request(handle)
                session.inspect(handle)
              end
```

Upload the access log to the log service (optional)
```yaml
# curiefense-log-patch.yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: curiefense-access-logs-filter
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: "curiefense"
spec:
  workloadSelector:
    labels:
      curiefense: "enabled"
  configPatches:
    - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            access_log:
              - name: "envoy.http_grpc_access_log"
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig"
                  common_config:
                    log_name: "send_GRPC_log_to_curielogger"
                    transport_api_version: "V3"
                    grpc_service:
                      google_grpc:
                        target_uri: "curielogger.curiefense:9001"
                        stat_prefix: "curielogger_grpc"
```
