### ISSUE TITLE
Envoy: output each value under its own key instead of a single value containing serialized json

### ISSUE THREAD

**Issue by xavier-rbz** [curiefense/curiefense#712]
**Is your feature request related to a problem? Please describe.**

In some deployment scenarios, customers prefer collecting logs through their existing infrastructure straight out of envoy, instead of having envoy send them over GRPC to curielogger, and then collecting logs from curielogger. That way, they may avoid using curielogger, knowing that they won't benefit from the prometheus metrics that it generates.

To make envoy output envoy metadata as json, the following envoy configuration can be used:
```
--snip--
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          use_remote_address: true
          skip_xff_append: false
          access_log:
            name: "envoy.access_loggers.file"
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              "path": "/tmp/out.log"
              "json_format":
                 protocol: "%PROTOCOL%"
                 (other fields)
                 cflog: "%DYNAMIC_METADATA(com.reblaze.curiefense:request.info)%"
--snip--
```

Curiefense's envoy HTTP filter outputs logs as a single value containing serialized json ([code](https://github.com/curiefense/curiefense/blob/0c88b4308f08f0aa88f96907455dfd7a4aee7fe2/curiefense/curieproxy/lua/accesslog.lua#L44)), whose [filter name](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#set) is `com.reblaze.curiefense`, and whose key is `request.info`. In environments where curielogger is used, this single value is extracted ([code](https://github.com/curiefense/curiefense/blob/main/curiefense/curielogger/cmd/grpc/server.go#L61)), and then de-serialised ([code](https://github.com/curiefense/curiefense/blob/main/curiefense/curielogger/cmd/grpc/server.go#L73)).

Alas, in environments where curielogger is *not* used, the output JSON contains a single serialized value, which is not convenient for eg. searching in elastic search.

**Describe the solution you'd like**

* Modify both curiefense's envoy HTTP filter so that it outputs each value under its own key, and avoids serializing data
* Modify curielogger so that is supports this new format. It would not have to de-serialize received data anymore
* (bonus) Document the format of data that is generated by curiefense's HTTP filter

If this is implemented, we would not need to serialize logged data, and then de-serialize it. There might even be a performance boost.
