### ISSUE TITLE
Can the "access_log" of "HttpConnectionManager" directly output the log information of curiefense in envoy

### ISSUE THREAD

**Issue by MicroOps-cn** [curiefense/curiefense#831]
I used to use envoy to output logs as follows:
```
filters:
  - name: envoy.filters.network.http_connection_manager
    typed_config:
      '@type': 'type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager'
      access_log:
        - name: envoy.file.access_log
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: /var/log/envoy/access.log
            log_format:
              json_format:
                '@timestamp': '%START_TIME%'
                bytes_sent: '%BYTES_SENT%'
                http_header_psn: '%REQ(Psn)%'
                http_referrer: '%REQ(Referer)%'
                http_x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
                ......
```
Directly output to the log file without an additional service, and then collect the log service through the agent provided by the log service.
But I didn't find a way to output "geo-city", "cf-rule-id" and other information to the log file through "access_log"
